const contacts = [
  {
    id: 1,
    name: "Сосорбарамын Энхтайван",
    position: "Дарга",
    phone: "96441416",
    email: "enkhtaivanenkhtaivan07@gmail.com",
  },
  {
    id: 2,
    name: "Батнэрэнгийн Болор",
    position: "Захиргаа, хүний нөөцийн ахлах мэргэжилтэн",
    phone: "80089213",
    email: "bnbolor@gmail.com",
  },
  {
    id: 3,
    name: "Шарбаатарын Дуламсүрэн",
    position: "Ерөнхий нягтлан бодогч",
    phone: "91914914",
    email: "sh.duka4915@yahoo.com",
  },
  {
    id: 4,
    name: "Баянжавын Одгэрэл",
    position: "Мэдээлэл, лавлагааны ажилтан (Нууцын ажилтан)",
    phone: "89139048",
    email: "bayanjawodgerel@gmail.com",
  },
  {
    id: 5,
    name: "Ганболдын Идэрсайхан",
    position: "Мэдээлэл, лавлагааны ажилтан",
    phone: "91000925",
    email: "ideree1330@gmail.com",
  },
  {
    id: 6,
    name: "Тулгажавын Дуламжав",
    position: "Архив, бичиг хэргийн ажилтан",
    phone: "99187197",
    email: "duuya.tulgajaw1005@gmail.com",
  },
  {
    id: 7,
    name: "Буджаргалын Баттуяа",
    position: "Үйлчлэгч",
    phone: "89284433",
    email: "battuya1111@gmail.com",
  },
  {
    id: 8,
    name: "Өнөрсайханы Ууганбаяр",
    position: "Сүлжээний инженер",
    phone: "80116374",
    email: "uugaa158@gmail.com",
  },
  {
    id: 9,
    name: "Тувшинжаргалын Давид",
    position: "Системийн инженер (Программ хангамжийн инженер)",
    phone: "80453001",
    email: "tdavid0522@gmail.com",
  },
  {
    id: 10,
    name: "Цогтбаярын Мөнгөнцоо",
    position: "Сүлжээний техникч",
    phone: "88082269",
    email: "tsogtbayrmongontsooj@gmail.com",
  },
  {
    id: 11,
    name: "Мөнххуягийн Баттер",
    position: "Сүлжээний техникч",
    phone: "80781027",
    email: "monhhuygbattur@gmail.com",
  },
  {
    id: 12,
    name: "Батжаргалын Эрдэнэбат",
    position: "Жолооч",
    phone: "89057000",
    email: "erdenebate280@gmail.com",
  },
  {
    id: 13,
    name: "Ганцооийн Хангай",
    position: "Цахилгаанчин",
    phone: "95106226",
    email: "gantsoojhangai02@gmail.com",
  },
];
export default contacts;